### ISSUE TITLE
Change wording of notification to "Caffeine enabled", not "Auto suspend and screensaver disabled"

### ISSUE THREAD

**Issue by Flimm** [eonpatapon/gnome-shell-extension-caffeine#173]
When you activate this program called Caffeine, you get this notification:

> Auto suspend and screensaver disabled

This is confusing to me. Didn't I just activate something? Why is it saying that something is "disabled"?

When you turn off Caffeine functionality, you get this notification:

> Auto suspend and screensaver enabled

Again this is confusing to me.

The icon is also confusing to me. Which one is "on"? Is it the icon of the full cup? Or the icon of the cup with steam but not liquid?

Here is my proposal:

1. Change the text of the notifications to say:

> Caffeine is now preventing your computer from automatically suspending or launching a screensaver

> Caffeine is no longer preventing your computer from automatically suspending or launching a screensaver

2. Regarding the icons, I would make the one that represents caffeine being off (normal suspend behaviour) to be an empty cup, and the one representing on to be the icon with steam.

**Comment by zorba128** [comment]
Late, but strong upvote.

Just got it installed and first thing that struck me is negated logic in notification - I'm never sure if I just enabled this tool or disabled. Noticed that today - after finishing my work I just wanted to make sure I disabled it. And I again had to read and understand notification message shouting words such as "screensaver" at me :)

I'd have much easier life it was something like:
- caffeine on/caffeine off
- stay awake mode on/stay awake mode off
- fresh coffee brewed/run out of coffee

One could append to this message some explanation of what really happened (the "Auto suspend ....") - but it should be in the very end - so that I dont have to read it :).

In general - just please use "enable" to tell state when coffeine is preventing system from going to sleep.

Thanks
