### ISSUE TITLE
longer timers

### ISSUE THREAD

**Issue by boyska** [eonpatapon/gnome-shell-extension-caffeine#296]
The default timers seems to have very low values. The shortest one is 5 minutes. Now, if I wanted to keep computer awake for 5 more minutes, wasn't it enough to move the mouse?

My usecase for caffeine is listening to music and leaving the computer unattended. In that scenario, what I need is something like 2h caffeine mode, while the longest one is 30 minutes.

Since there is no way to customize the duration, can you at least increase the default timers?

**Comment by stuarthayhurst** [comment]
Which version of Caffeine are you running? The version in `master` has support for customisation:
![image](https://github.com/eonpatapon/gnome-shell-extension-caffeine/assets/33733427/8b31d8af-1295-47ca-b777-12973be42375)

I can't remember if this has made it to a release or not yet, but a new one should be coming out soonish, whenever the GNOME 45 port is merged.

**Comment by boyska** [comment]
>Which version of Caffeine are you running? The version in `master` has support for customisation:

oh, that's nice! I'm using version 44-2 from debian bookworm.

**Comment by stuarthayhurst** [comment]
Ah, looking at the merge history, v45 was the first version to allow configuration, currently only Debian testing have v48.
The latest version of `master` currently supports GNOME 43 and 44, since you're on Debian stable, this should be supported.

I don't know if it'll get backported, it seems unlikely as it's not a very important package, so you may be better off installing from source, or installing from https://extensions.gnome.org/extension/517/caffeine/ instead.

**Comment by boyska** [comment]
ok, thanks for clarifying what is compatible with what: I would have get 
confused otherwise :)

**Comment by pakaoraki** [comment]
This is the current range timers:
- 5, 10, 30 minutes
- 10, 20, 45 minutes
- 15, 30, 60 minutes
- 20, 40, 75 minutes
- 30, 50, 80 minutes

Let me knows if it need adjustment.

**Comment by parskongar** [comment]
@pakaoraki I'm so sorry to bother you, but I was just wondering, why don't you support custom inputs, for example three input boxes next to each other.

**Comment by Ana06** [comment]
I would like to have even a higher range timer. Some use cases:
- When using two computers and I want to see the status of a task that takes long to execute in the other
- When I want to execute a very long task over night while I sleep

An extra range timer with `30 minutes, 2 hours, 8 hours` would fit this needs. 

I also like the idea of custom inputs. In that case, I think it would be nice to show any multiple of 30 higher or equal than 60 in hours in the menu (example: `20 minutes , 30 minutes, 1 hour, 80 minutes, 1.5 hours, 4 hours, 260 minutes, 5.5 hours, 365 minutes`).

In general, it would also be nice to display times as `HH:MM:SS` (instead of the current `MM:SS`) for times longer than an hour. Examples: `2:32, 12:32, 1:12:32, 11:12:32`

**Comment by pakaoraki** [comment]
I will propose a revamp with custom values:

![Screenshot from 2024-03-05 23-05-36 resized](https://github.com/eonpatapon/gnome-shell-extension-caffeine/assets/83842133/78fd0269-6917-4c24-b8f2-ba6eb5829c8d)

**Comment by stuarthayhurst** [comment]
> I will propose a revamp with custom values:
> 
> ![Screenshot from 2024-03-05 23-05-36 resized](https://private-user-images.githubusercontent.com/83842133/310293713-78fd0269-6917-4c24-b8f2-ba6eb5829c8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzY3OTYsIm5iZiI6MTcwOTY3NjQ5NiwicGF0aCI6Ii84Mzg0MjEzMy8zMTAyOTM3MTMtNzhmZDAyNjktNjkxNy00YzI0LWI4ZjItYmE2ZWI1ODI5YzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIyMDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmJhZjNkN2IzMmZjODM1MjBjZjk0Y2IwYTkyNzM0MDZlZDY4Mzg1NGEwNmQ3Nzk3MTI0MjdlNDc3N2IxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.imtdb0aYDxLD8fIuJRSG_pMIc4TRjL3V5pwlDpck33I)

Ooh looks good, I'd be happy to review that if you submit a PR

**Comment by pakaoraki** [comment]
I'll try to PR this soon.
