### ISSUE TITLE
Update the source code

### ISSUE THREAD

**Issue by actrawave** [eonpatapon/gnome-shell-extension-caffeine#344]
Hi, if you will install Caffeine from extensions.gnome.org, you will have the 55th version installed, but if you will install it from source you will have 54th version. Please update the source code!

**Comment by stuarthayhurst** [comment]
The code on the extensions site and the source code here are the same, the version numbers are just out of sync.

If an upload is rejected to extensions.gnome.org and it has to be reuploaded, the version number is incremented twice, falling out of sync.

@eonpatapon Could correct the tag and metadata.json in the repo, but the source code itself is fine otherwise :)
