### ISSUE TITLE
Outdated according to Gnome

### ISSUE THREAD

**Issue by j0hannes** [eonpatapon/gnome-shell-extension-caffeine#45]
just a hint

**Comment by l300lvl** [comment]
@j0hannes i see you've posted this issue on multiple extensions, perhaps you were still running the dev version of 3.16, i.e 3.15.91 or 3.15.92? This extension was updated at least a week ago to support 3.16 and pushed to the extensions site where, and ymmv, for me as soon as I updated to 3.16 it was available and not marked as outdated. There could be a bug on the extensions site though, so I am curious.

**Comment by j0hannes** [comment]
The extension site showed most extensions to me as outdated. gnome-shell-extension-prefs allowed me to update every extension, but caffeine. This one was the only one shown in the application which was marked as outdated and had no update option available.

When I looked it up now, I found that caffeine was gone (maybe I accidently removed it from the list?). I was able to add it again via the extension site and no error is shown anymore.

**Comment by l300lvl** [comment]
@j0hannes on the extensions site where it showed the "outdated" button, did you also see the update arrow icon for all the _other_ extensions? was that arrow visible for caffeine, or did it just show outdated? it could have just been a minor glitch since you have multiple extensions installed that were outdated, and perhaps the extensions site just didn't load all the way even. glad you got it working though!

**Comment by j0hannes** [comment]
There was no update button on the extension site - and I visited (and reloaded) it several times as I had read that there but be an option to update the installed extensions if they are compatible with one's Gnome version.

**Comment by l300lvl** [comment]
If you didn't see the update button for any extension, that slims down the possibilities a lot. The problems I would guess are, and not knowing arch I can't say for sure, but perhaps you updated your system in between actually updating the extensions? Do you see updates on the site for any extensions you maybe didn't update, now?

If you did not update your system and are sure you were running 3.16 the whole time, and not 3.15.91 or .92 than perhaps the browser plugin wasn't loaded at the time somehow?

Otherwise, I would guess you found a bug, and this would be either gnome/gnome-shell or arch related.

**Comment by j0hannes** [comment]
I've never seen any update option on the extension site, but in the gnome-shell-extension-prefs list.

I hadn't updated any of the extensions for quite a while. After upgrading to Gnome 3.16, I noticed that almost no extension would be working and tried to update via the extension page.

It isn't clear to me how to track the reason for this 'malfunction' down. That's why I don't really feel like posting a bug report to, say, Gnome Shell. At last, I can't even reproduce it now.

But caffeine seems to work now. Thanks for your efforts - and that nice little helper.

**Comment by l300lvl** [comment]
No problem. I am glad to help, but I must say thanks go to @eonpatapon for the Caffeine extension, I only commented here to try to determine the specific issues you are having as I was a bit curious as to your specific gnome-shell issue. Which I still am, but alas, I'm still not sure if I came across right. I was asking if you updated arch/gnome-shell.

If you never ever ever see an extension update on the extension website, the best place to discuss this problem would be on the arch support forums/irc, as this would seem to be a problem with the gnome extensions browser plugin. You say the site showed you the extensions were outdated, but did not show you any updates, which tells me the browser plugin was possibly outdated, or you updated your arch system during or after trying to update the extensions from the site itself, so you may see extension updates available sometime in the future. But still, you should report this to arch at the very least so it doesn't go unseen.
