### ISSUE TITLE
Caffeine does not disable screensaver

### ISSUE THREAD

**Issue by googol42** [eonpatapon/gnome-shell-extension-caffeine#47]
Hello,

I am using Arch Linux with gnome shell 3.16. I have xscreensaver together with xss-lock.

However, Caffeine does not work.
- First I tried the auto disabling feature (disable when an application is running in fullscreen mode). I saw that Caffeine realised that VLC is now running in fullscreen mode (I saw it on my second screen).
- Then I disabled it manually. No luck.

(And I also tried it with only one screen.)

I guess it is due to my setup. (It took me a while to get my screensaver to work... whyever...).

I am happy to help debugging this... Btw, this extentions seems quite cool.. hope we can sort this issue out :)

Regards

**Comment by nilesr** [comment]
From what I can tell, Caffeine is not compatible with xss-lock or xautolock. It seems to work by communicating with the gnome session manager, so it works with gnome-screensaver

**Comment by l300lvl** [comment]
As I recall there was(is still) a lot of grief with Gnome by the creator/maintaner of xscreensaver. Mostly over why gnome forked xss and then eventually dropped "screensavers" all together. Unless you can actually get it working from the gnome side, that being on the gnome-screensaver/caffeine end, you won't get much support if ANY from the xss dev. He has spent far too many years in his opinion to support Gnome Shell(because gnome dropped support for him). The better option would be for someone to fork the thing again and get xss working as a plugin for gnome-screensaver. Which probably also won't happen.

Alternatively you can probably use Caffeine and not this which is Caffeine for Gnome-Shell. Caffeine itself does work with X-s-s, but has no pretty front end compatibility with G:S which should not bother you since x-s-s in it's current state is also ugly with G:S.

**Comment by hako1** [comment]
I am using Ubuntu 17.04 Gnome. The Caffeine extension does not inhibit xscreensaver.
I found jefferyto's faux-gnome-screensaver [https://github.com/jefferyto/faux-gnome-screensaver] which solves the problem for me. Just install as described.
Easy solution.

**Comment by chovy** [comment]
I'm having the problem on 18.04

**Comment by eonpatapon** [comment]
Caffeine uses gnome session manager inhibitors. It means the screensaver or screenlock needs to be integrated with gnome session manager for caffeine to work
